# Harmony Jekyll theme general configurations 

# Base URL
baseurl: /sqlite-analyzer

# Site live URL
url: http://novoda.github.io

# Localhost 
# url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: SQLite Analyzer by Novoda
  # Little description about your site
  description: Code generation for Java/Android database access.
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  meta_description: > # 
   Generates java/android database access code by analysing sqlite migration files or sqlite databases, keeping full control of what code is generated.
   Sourced on Github - https://github.com/novoda/sqlite-analyzer
  basetheme: theme-base-02 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Novoda
    email: contact@novoda.com
    url: http://novoda.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social: 
    github: novoda
    twitter: novoda
    facebook:
    gplus: +Novoda
    dribble: 
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: true

  
project:
  name: sqlite-analyzer
  
# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments 

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
